### ISSUE TITLE
Cannot set property GrpcClient ...

### ISSUE THREAD

**Issue by caginyunus** [jacobobryant/mystery-cows#9]
Hi, I am getting the following error when I run ./task dev:

firebase | ⚠  functions: Cannot set property GrpcClient of #<Object> which has only a getter
firebase | ⚠  Your function was killed because it raised an unhandled error.

Same error also appears when a user tries to join a room another user created.

**Comment by jacobobryant** [comment]
I just ran this project again myself (it's been a while) and got the same error. I ran `npm update` and then it went away. I've updated `package.json` and `package-lock.json`. Also I changed the dev instructions in the README a bit since it looks like it's better to run the firebase emulator in a separate terminal window.

Anyway, could you see if the following fixes it for you?

1. `git pull`
2. `npm install`
3. `./task dev`
4. (After Shadow CLJS builds finish) `firebase emulators:start`

**Comment by caginyunus** [comment]
Thanks for quick return. I didn't get any error but there are two issues:
* If a player creates a room, then he can't leave.
* A player can't enter to a room created by another player.

**Comment by jacobobryant** [comment]
I didn't run into those issues myself--are there any error messages, either in the terminal window or in the browser dev console? Also in the network tab in the browser dev tools, you should see a successful POST request when clicking "Leave game".

It sounds like there's some issue with calling cloud functions, since creating a game is handled by submitting a transaction directly to firestore, but leaving games and joining existing games is handled via cloud functions. If you don't see any errors, you could add some print statements to the `:leave-game` handler in `src/cows/fn.cljs`, e.g.:

```clojure
(defmethod handle :leave-game
  [{:keys [auth/uid]} game-id]
  (println "leave-game")
  ...
```

Then in the firebase terminal window, you should see this:

```clojure
i  functions: Beginning execution of "handle"
>  leave-game
i  functions: Finished "handle" in ~1s
```

**Comment by caginyunus** [comment]
I am not sure what changed but it works now!

**Comment by jacobobryant** [comment]
Awesome!
